server:
   port: 8080

spring:
  application:
    name: shop-server
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
shop:
  jwt:
    secretKey: lejings
    ttl: 3600000
    tokenName: token


mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: top.lejings.shoppojo.VO
  configuration:
    mapUnderscoreToCamelCase: true
